version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./certs:/https/ssl/certs
      - ./certs:/https/ssl/private
      
    networks:
      - sportingstats-network

  frontend:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
      args:
        - VUE_APP_BACKEND_URL=https://localhost:5000
    environment:
      - NODE_ENV=development
      - VUE_APP_BACKEND_URL=https://localhost:5000
    ports:
      - "8080:8080"
      - "3001:3001"
    networks:
      - sportingstats-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
      
    depends_on:
      - frontend
      - backend
    networks:
      - sportingstats-network

networks:
  sportingstats-network:
    driver: bridge
