version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./certs:/etc/nginx/ssl
    networks:
      - sportingstats-network

  frontend:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
      args:
        - VUE_APP_BACKEND_URL=https://sportingstats.ca:5001
    environment:
      - NODE_ENV=production
      - VUE_APP_BACKEND_URL=https://sportingstats.ca:5001
    ports:
      - "8080:8080"
      - "3001:3001"
    volumes:
      - ./FrontEnd/public/images:/usr/share/nginx/html/public/images
    networks:
      - sportingstats-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
      - ./FrontEnd/public/images:/usr/share/nginx/html/public/images
      - ./dhparam.pem:/etc/nginx/ssl/dhparam.pem  # Map dhparam.pem file
      
    depends_on:
      - frontend
      - backend
    networks:
      - sportingstats-network

networks:
  sportingstats-network:
    driver: bridge
